openedx/opaque-keys

opaque_keys/edx/locator.py

To make it easier to understand what's wrong when trying to create a key that contains characters not allowed in the key's fields.

Better error message when field contains invalid chars.

---

opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_asset_locators.py

In course when user uploads an asset which has percentage`%` in their filenames; it faces issue on  `course re-run`.
[opaque_keys/edx/locator.py#L98](https://github.com/edx/opaque-keys/blob/master/opaque_keys/edx/locator.py#L98)
Above `Regex` parses asset names and when an asset has `%` in its `name` this Regex  fails to compile it. *(Split to Split)*
Updated the `Regex` to handle the case where if there is a `%` in asset name, it can parse successfully.
[TNL2098](https://openedx.atlassian.net/browse/TNL-2098)

Regex does not match asset url when it contains spaces

---

opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_asset_locators.py

`Schedule & Details` page of the course was breaking because it had empty `course_image`. 
with the empty image path, the assert locator throws `InvalidKeyError`. 
Mongo & Split were behaving differently, when a asset path is empty. Split raise `InvalidKeyError` but Mongo does not. 
[TNL-2435](https://openedx.atlassian.net/browse/TNL-2435)

 Fixed Broken page in "Schedule & Details" due to course image

---

opaque_keys/__init__.py
opaque_keys/tests/test_opaque_keys.py

@brianhw is this what you had in mind ?
I'm looking to add a test for this, incase of UnicodeDecodeError, should we return nothing or reraise ?

Catch UnicodeEncodeError.

---

opaque_keys/__init__.py
opaque_keys/edx/locator.py
opaque_keys/tests/test_opaque_keys.py
pylintrc
pylintrc_tweaks

This commit actually fixes the violations rather than ignore them.

Clean literal-used-as-attribute Pylint violations

---

setup.py

This package is needed by ccx-keys.

Including opaque_keys.edx.tests in exported packages

---

setup.py

We definitely need a later version of six to support python_2_unicode_compatible. Pinning the other requirements to avoid potential issues with major version bumps breaking this library.
ECOM-4016

Pinning requirements

---

CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_block_usage_locators.py
setup.py

Okay folks, thank you for your patience. I think this is now in a reviewable state.
Looking at the progress page of a fairly large course (~1.3K blocks) here are three things that happen over and over to OpaqueKeys 
1. Hashing (114K times)
2. Serialization to unicode (49K times)
3. Equality checks (19K times)
This PR tries to address those issues by:
1. Storing the hash explicitly as an integer attribute, so we can throw it back with no work.
2. Storing the serialized unicode representation (which is simple, since that's usually how it's constructed).
3. Intern the OpaqueKeys.
The third one helps avoiding the extra work of hashing and serialization, but it also makes equality faster because we can short circuit them using object identity and hash value (both of which are cheap to check). …

PERF: Optimize key hashing and equality comparison

---

opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_asset_locators.py
opaque_keys/edx/tests/test_block_usage_locators.py
opaque_keys/edx/tests/test_course_locators.py
opaque_keys/edx/tests/test_library_locators.py
opaque_keys/edx/tests/test_library_usage_locators.py
setup.py

https://openedx.atlassian.net/browse/ECOM-5345
The key url regular expression was flawed in that it allowed trailing newlines. I haven't found a way yet via regex to detect trailing newlines in the complex regex that the code needs, so a separate check for trailing newlines was added. Tests were also added for other important locators/keys.
@cpennington @ormsbee @cpennington @adampalay @feanil @rlucioni PTAL.

Protect keys/locators against trailing newlines.

---

CHANGELOG.rst

@edx/platform-team I forgot to update the CHANGELOG in the previous library version. This PR fixes the omission. Please review.

Update CHANGELOG for version 0.3.4

---

CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_block_usage_locators.py
setup.py

Minus the horrible issue that caused a hotfix. The value of `._unicode` always has to be derived from the parsed key, instead of trusting input into `from_string`

Re-applying Optimizations

---

CHANGELOG.rst
opaque_keys/edx/locations.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_aside_keys.py
opaque_keys/edx/tests/test_deprecated_locations.py
opaque_keys/edx/tests/test_properties.py
setup.py

Cut down on the number of deprecation warnings generated, by avoiding usage of deprecated properties where feasible.
Also fixed a failure case uncovered by Hypothesis, where slashes were being allowed (and ignored) at the end of usage keys using the deprecated serialization format.  Cale thinks it's highly unlikely that any such strings made it through our existing parser into production data.
Finally, disabled a Hypothesis health check for slow data generation, which seems to be routinely triggered now for our existing Travis configuration.

PLAT-1885 Less usage of deprecated properties

---

.gitignore
.travis.yml
manage.py
opaque_keys/edx/django/models.py
opaque_keys/edx/django/tests/models.py
opaque_keys/edx/django/tests/test_models.py
pytest.ini
requirements-with-django.txt
settings/base.py
settings/test.py
setup.py
tox.ini

https://openedx.atlassian.net/browse/EDUCATOR-2011
The Educator team would like to move the code in lms/djangoapps/completion to its own repository (and then pip install it into edx-platform).  The completion models depend on OpaqueKeyFields for tracking course ids and block ids.  This pull request copies the code in `openedx.core.djangoapps.xmodule_django.models` and `openedx.core.djangoapps.util.model_utils`.  This allows us to de-couple the dependency on edx-platform for the completion model definitions.

Extract OpaqueKeyFields from edx-platform.

---

.gitignore
CHANGELOG.rst
requirements-with-django.txt
setup.py

Move pytest-django to the testing requirements.  Also added missing changelog entries and added a .gitignore entry for the new pytest cache directory name.

PLAT-2066 Remove pytest-django from extras_require

---

opaque_keys/edx/tests/test_properties.py
opaque_keys/tests/strategies.py
test-requirements.txt
tox.ini

Tests were failing with the following stacktrace:
```
__________ ERROR collecting opaque_keys/edx/tests/test_properties.py ___________
opaque_keys/edx/tests/test_properties.py:13: in <module>
from opaque_keys.tests.strategies import keys_of_type
opaque_keys/tests/strategies.py:32: in <module>
@strategies.cacheable
E   AttributeError: 'module' object has no attribute 'cacheable'
__________ ERROR collecting opaque_keys/edx/tests/test_properties.py ___________
opaque_keys/edx/tests/test_properties.py:13: in <module>
from opaque_keys.tests.strategies import keys_of_type
opaque_keys/tests/strategies.py:32: in <module>
@strategies.cacheable
E   AttributeError: 'module' object has no attribute 'cacheable'
=================================== FAILURES =================================== …
```

Account for change in hypothesis library

---

opaque_keys/edx/django/models.py
opaque_keys/edx/django/tests/test_models.py

Different modules use an Opaque key subclass [as unique id](https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/content/course_overviews/models.py#L55). And, the opaque key field class is implemented in a way that you have to pass an instance of whatever the `KEY_CLASS` is for lookup. Meaning, one cannot do `co = CourseOverview.objects.get(id='some-course-overview-key')` but instead one has to retrieve a `CourseKey` instance and use that as the id value.
This PR changes this so the `KEY_CLASS` lookup is done if a string is used for the ORM query, making it easier to write queries and also making it easier to use admin forms that involve opaque keys subclass fields.
The reason why this makes it easier to use admin forms is because django admin will automatically handle …

Parse value from string to prepare django ORM query.

---

opaque_keys/edx/locations.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_course_locators.py
opaque_keys/edx/tests/test_deprecated_locations.py

These are old deprecated methods (with replacements 'unicode' and
'from_string' respectively). We don't believe any other code in
the Open edX platform is using them anymore.
DEPR-16

Drop to_dreprecated_string and from_deprecated_string

---

CHANGELOG.rst
setup.py

Normally I wouldn't bother with a full review, but since this is going from 0.x to 1.0, it feels momentous enough to check in.
The major version bump is because of DEPR-16 and us removing the to_deprecated_string and from_deprecated_string API.

Bump version to 1.0.0 and add a changelog entry

---

setup.py

Unfortunately, we use test mixins for https://github.com/edx/ccx-keys , so preventing bundling causes us to not be able to run those tests. Alternate solutions welcome.

ccx uses the tests packages for Mixins.

---

CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/django/models.py
opaque_keys/edx/keys.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_default_deprecated.py
opaque_keys/edx/tests/test_is_course.py
opaque_keys/edx/tests/test_library_locators.py
opaque_keys/edx/tests/test_library_usage_locators.py
opaque_keys/edx/tests/test_locators.py
opaque_keys/tests/strategies.py
setup.py

This PR moves some key-related code for new Blockstore-based content out of `edx-platform` and into `opaque-keys`.
It includes: 
* A new abstract key type, `LearningContextKey`, which identifies a _learning context_. A learning context may be a course, a library, or other types in the future.
- All `CourseKey`s are `LearningContextKey`s
* A new `LibraryLocatorV2` key type which is a type of `LearningContextKey` that identifies a Blockstore-based content library.
- Note that unlike the existing modulestore-based [`LibraryLocator`](https://github.com/edx/opaque-keys/blob/72e54d1d40aa8209f3eef5238f64794f5804895f/opaque_keys/edx/locator.py#L378), calling `isinstance(LibraryLocatorV2, Coursekey)` will return `False` because we now have this more abstract type to use. Yay.
* A new …

Add New Blockstore-related Opaque Key Types

---

conftest.py
opaque_keys/edx/tests/test_properties.py
opaque_keys/tests/strategies.py
requirements/base.txt
requirements/dev.txt
requirements/django.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/test.txt
requirements/travis.txt
tox.ini

- Change Hypothesis import due to internal API change in 4.53.2
- Reduce Hypothesis [`max_examples`](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.max_examples) for the CI profile to keep test times roughly as they were with older version. This drops average test run time from approximately 15 to 10 minutes, but it would have increased to 30 minutes without this change, with timeouts due to >10 minute pauses for some tests.
- Fix indentation

Fix `make upgrade` by bumping pip-tools version; run upgrades

---

CHANGELOG.rst
MANIFEST.in
requirements/base.in
requirements/dev.txt
requirements/test.in
requirements/travis.txt
setup.py

Note that some constraints previously had a trailing single-quote, although it doesn't seem to have caused any harm.
This extracts the requirements fix from https://github.com/edx/opaque-keys/pull/116 but does not drop Python 2.7.

Fix setup.py to use requirements dir; drop max version constraints

---

.travis.yml
MANIFEST.in
Makefile
requirements/dev.txt
requirements/django-test.in
requirements/django-test.txt
requirements/django.in
requirements/django.txt
requirements/doc.in
requirements/doc.txt
requirements/test.in
requirements/test.txt
setup.py
tox.ini

This also changes the purpose of `django.in` from being a "core + django + django" deps collection to just being the extra deps required for django support.

Restore [django] extra

---

.travis.yml
opaque_keys/edx/django/models.py
opaque_keys/edx/django/tests/models.py
opaque_keys/edx/keys.py
opaque_keys/edx/locations.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_locators.py
opaque_keys/tests/strategies.py
requirements/constraints.txt
requirements/dev.txt
requirements/django-test.txt
requirements/django.in
requirements/django.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/test.in
requirements/test.txt
requirements/travis.txt
setup.py
tox.ini

Relevant JIRA : [https://openedx.atlassian.net/browse/BOM-1538](https://openedx.atlassian.net/browse/BOM-1538)
- Removed Python 2.7 
- Added Python 3.8 to testing
- Removed Django versions < 2.2
- Ran make upgrade
- Fixed some quality failures

BOM-1538 : Add Python 3.8 to testing

---

CHANGELOG.rst
opaque_keys/edx/django/models.py
setup.py

JIRA: [BOM-1879](https://openedx.atlassian.net/browse/BOM-1879)
`Support for the context argument of Field.from_db_value() and Expression.convert_value() is removed.`
https://docs.djangoproject.com/en/3.0/releases/3.0/#features-removed-in-3-0

Fixed django 3.0 warning

---

requirements/constraints.txt
requirements/dev.txt
requirements/django-test.txt
requirements/doc.txt
requirements/test.txt
requirements/travis.txt

- Pinned `importlib-metadata==1.7.0` as `version>1.7.0` is causing conflicts for python35 in running `make upgrade`.

Pin importlib-metadata to 1.7.0 for python35

---

requirements/constraints.txt
requirements/dev.txt
requirements/django-test.txt
requirements/django.txt
requirements/doc.txt
requirements/test.txt
requirements/travis.txt

- `importlib-metadata<2.0.0` was causing conflicts in running `make upgrade` with `python3.5`.
- Unpinned `importlib-metadata` constraint after fixing the issue in https://github.com/pypa/virtualenv/pull/1953 and https://github.com/tox-dev/tox/pull/1682.

Unpin importlib-metadata constraint

---

requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/django-test.txt
requirements/doc.txt
requirements/test.txt
requirements/travis.txt

`pytest-django=4.0.0` requires `pytest>=5.4` which is currently pinned to `pytest<5.3` hence causing the build failure in `python requirements upgrade`: https://build.testeng.edx.org/job/opaque-keys-upgrade-python-requirements/74/console
So pinning the version untill `pytest<5.3` constraint is removed.

Pinned pytest-django<4.0.0

---

.travis.yml
CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/django/models.py
opaque_keys/edx/tests/test_course_locators.py
opaque_keys/tests/test_opaque_keys.py
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/django-test.txt
requirements/django.txt
requirements/doc.txt
requirements/test.txt
requirements/travis.txt
setup.py

Upgrade build was failing because of Django version conflicts https://build.testeng.edx.org/job/opaque-keys-upgrade-python-requirements/88/console 
So added Django constraint, removed previous constraints which are not required now. 
Updated the PyPI build to be deployed using `Python3.8`. 
Bumped the version to `2.2.0` and updated the `CHANGELOG`.

Remove constraints

---

requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/django-test.txt
requirements/django.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/test.txt
requirements/travis.txt

**Issue:** [BOM-2548](https://openedx.atlassian.net/browse/BOM-2548)
- The repo didn't have common constraints in it. Adding common constraints resolved the upgrade conflict which was causing the [requirements upgrade job failure](https://build.testeng.edx.org/job/opaque-keys-upgrade-python-requirements/104/console).

BOM-2548: Add common constraints

---

CHANGELOG.rst
setup.py

All Python dependencies were upgraded in this PR: https://github.com/edx/opaque-keys/pull/182
This PR bumps the patch version of the package.

chore: Bump version to 2.2.1 after upgrading dependencies.

---

.readthedocs.yml
.travis.yml
docs/conf.py
opaque_keys/edx/keys.py
opaque_keys/edx/locator.py
tox.ini

We do this so that we can catch any issues with the RSTs before they
cause build failures in the final build.

docs: Build the docs as a part of CI.

---

requirements/pip-tools.txt

This failure started happening in the automated requirements upgrade:
https://github.com/openedx/XBlock/runs/5100983778?check_suite_focus=true
The bug was being caused by an interaction between pip and pip-tools, described here:
https://github.com/jazzband/pip-tools/issues/1558
The bug is fixed in pip-tools==6.5.0 - from this PR:
https://github.com/jazzband/pip-tools/pull/1567
Just bump the version manually to get the automated upgrades working again.

Manually upgrade pip-tools to 6.5.0 to fix pip/pip-tools bug.

---

Makefile
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/django-test.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.in
requirements/pip.txt
requirements/test.txt

Updated the upgrade target script to check the compatibility of upgraded pip and pip-tools versions.
For reference, look at this https://github.com/openedx/edx-repo-health/pull/271 for new check added in edx-repo-health.

fix: Install pip and pip-tools in upgrade script

---

.github/workflows/ci.yml
CHANGELOG.rst
opaque_keys/__init__.py
tox.ini

- Added support for Django 4.2
- Issue: https://github.com/edx/upgrades/issues/388

fix: Added support for Django42

---

CHANGELOG.rst
mypy.ini
opaque_keys/__init__.py
opaque_keys/edx/django/models.py
opaque_keys/edx/django/tests/models.py
opaque_keys/edx/django/tests/test_models.py
opaque_keys/edx/keys.py
opaque_keys/edx/locations.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/__init__.py
opaque_keys/edx/tests/test_course_locators.py
opaque_keys/edx/tests/test_library_locators.py
opaque_keys/edx/tests/test_library_usage_locators.py
opaque_keys/edx/tests/test_properties.py
opaque_keys/tests/strategies.py
pytest.ini
requirements/base.in
requirements/base.txt
requirements/django-test.txt
requirements/doc.txt
requirements/test.in
requirements/test.txt
setup.py
tox.ini

This adds type hints to opaque-keys, including to the CI build so that type rules are enforced before PRs can be merged.
This is actually aimed to help with edx-platform development, because once these type hints are in place, mypy can be used to check types of modules in edx-platform - see https://github.com/openedx/edx-platform/pull/32591 for example. Currently mypy just treats any OpaqueKey type as `Any` which is not helpful.
Some of the variables are of type `ObjectId` but this gets broadened automatically to `Any` because we're using an old version of `pymongo` that lacks type annotations. Once we upgrade `pymongo`, we'll have a more specific `ObjectId` type working.
Left for future:

feat: Add type hints

---

CHANGELOG.rst
MANIFEST.in
opaque_keys/__init__.py
opaque_keys/edx/django/models.py

My last PR #256 wasn't *quite* working with `mypy` in edx-platform. It was working fine in "editable" mode with `python setup.py develop` or `pip install -e .` but when installed via `pip install edx-opaque-keys==2.5.0` or `python setup.py install`, the important `py.typed` marker file was missing.
I thought that using `include_package_data=True` was sufficient, but it turns out I also needed to add a line to `MANIFEST.in`.
With this change, the `py.typed` file is installed and mypy will use the type hints added in #256.
------
I also added type hints for the django fields like `UsageKeyField`. This only works because of the django-stubs mypy plugin that we use in edx-platform, and requires setting a "private" class attribute to define the types, but it seems to work very well. Now mypy …

fix: type hints weren't installed properly, add type hints for Django Fields

---

requirements/ci.in
requirements/ci.txt
requirements/dev.txt

- Removed `tox-battery` from requirements and updated `tox` to `v4`.

fix: remove tox-battery and update tox

---

.github/workflows/ci.yml
opaque_keys/__init__.py
setup.py

Previously it could be empty but now PyPI throws an error when you try
to publish with an empty long description.
Fix that, and bump the version.  We're also updating the django
classifiers to be more accurate.

build: Add a long_descriptino which is now a required field.

---

CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_asset_locators.py
opaque_keys/edx/tests/test_block_usage_locators.py
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/django-test.txt
requirements/doc.txt
requirements/pip.txt
requirements/test.txt

https://pymongo.readthedocs.io/en/4.4.0/migrate-to-pymongo4.html#son-items-now-returns-dict-items-object
pymongo==4.4.0 [supports](https://pypi.org/project/pymongo/4.4.0/) Mongo 7 so we are good to go.

chore: upgrade pymongo.

---

opaque_keys/edx/locator.py

* Trim down BundleVersionLocator docstring to take up less space
* Emit warning when constructing a BundleVersionLocator
* Update other "Blockstore" references to "Learning Core"
https://github.com/openedx/public-engineering/issues/238

docs: update deprecated Blockstore references

---

CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/keys.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_collection_locators.py
setup.py

Creates `LibCollectionKey` and `LibCollectionLocator`
- Github Issue: https://github.com/openedx/modular-learning/issues/228
- This change is used on: https://github.com/openedx/edx-platform/pull/35383
- Internal ticket: https://tasks.opencraft.com/browse/FAL-3785
- Check all the code
- Verify that the test covers the changes

feat: LibraryCollectionKey and LibraryCollectionLocator created [FC-0062]

---

CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/keys.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_container_locators.py
setup.py

- Refactor `LibraryCollectionKey` to `LibraryItemKey` to use it as the general class for `LibraryCollectionLocator` and `LibraryContainerLocator`.
- Creation of `LibraryContainerLocator`
- Add `LibraryUsageLocatorV2` also as `LibraryItemKey`
- Github issues:
- https://github.com/openedx/openedx-learning/issues/282
- https://github.com/openedx/frontend-app-authoring/issues/1704
- Used in: https://github.com/openedx/edx-platform/pull/36379
- Internal ticket: [FAL-4108](https://tasks.opencraft.com/browse/FAL-4108)
- Check all the code.
- Verify that the test covers the changes.

feat: Create `LibraryContainerLocator` for Library Containers [FC-0083]

---

CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/keys.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_collection_locators.py
opaque_keys/edx/tests/test_container_locators.py

As discovered in https://github.com/openedx/edx-platform/commit/24ec901b0c261f017eb7f760698598b57d261d57#r155569458 some of our new library opaque keys use "lib_key" for the parent library key and others use "library_key". We should make this consistent before Teak.
The older v1 library keys continue to use `library_key` but I don't care as much if they're inconsistent. It's more important that the v2 keys are self-consistent. **This way, whether we have a key to a container or a to an XBlock, we can use .lib_key to get the library key**.
Dependencies: This is safe to merge anytime _after_ the edx-platform PR https://github.com/openedx/edx-platform/pull/36563 has merged. That PR can be merged anytime.
Private ref: FAL-4147

feat: rename 'library_key' to 'lib_key' on v2 locators for consistency [FC-0083]

---

CHANGELOG.rst
opaque_keys/__init__.py
opaque_keys/edx/django/models.py
opaque_keys/edx/django/tests/models.py
opaque_keys/edx/django/tests/test_models.py
opaque_keys/edx/keys.py
opaque_keys/edx/locator.py
opaque_keys/edx/tests/test_collection_locators.py
opaque_keys/edx/tests/test_container_locators.py
setup.py

The opaque keys used for items in libraries are:
* LibraryUsageLocatorV2 ( a UsageKey - the superclass usagekey is for XBlocks anywhere). Well established.
* LibraryCollectionLocator (a LibraryItemKey - a new superclass for non-XBlock items in libraries). New-ish.
* LibraryContainerLocator (a LibraryItemKey - a new superclass for non-XBlock items in libraries). New.
Thinking about this, it's going to be very confusing that we use the term "item" for anything in a library but XBlock keys in libraries (LibraryUsageLocatorV2) are not LibraryItemKeys. It's also weird that the base UsageKey is for XBlocks anywhere but the base LibraryItemKey  is for two different types of things and is specific to libraries.
This PR clears up this and makes it consistent via a slight breaking change to the …

Consistency fix (breaking): LibraryItemKey is replaced by CollectionKey and ContainerKey
